# .kodiak.toml
version = 1

[merge]
method = "squash"
delete_branch_on_merge = true
dont_wait_on_status_checks = ["WIP"] # handle github.com/apps/wip

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true # remove html comments to auto remove PR templates
